apiVersion: v1
kind: Secret
metadata:
  name: keycloak-admin-credentials
  namespace: keycloak
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: password
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-postgres-credentials
  namespace: keycloak
type: Opaque
stringData:
  POSTGRES_USER: keycloak
  POSTGRES_PASSWORD: password
  POSTGRES_DB: keycloak
  PGDATA: "/data/pgdata"
