apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: keycloak
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      restartPolicy: Always
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:25.0
          args: ["start-dev"]
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-credentials
                  key: KEYCLOAK_ADMIN_PASSWORD

            - name: KC_DB
              value: "postgres"
            # - name: POSTGRES_DB
            #   valueFrom:
            #     secretKeyRef:
            #       name: keycloak-postgres-credentials
            #       key: POSTGRES_DB
            - name: KC_DB_URL
              value: "jdbc:postgres://keycloak-psql:5432/keycloak"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-credentials
                  key: POSTGRES_USER
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: KC_DB_URL_HOST
              value: keycloak-psql
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"

            - name: KC_LOG_LEVEL
              value: TRACE
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"

            # - name: KC_PROXY
            #   value: "edge"
            # - name: KC_HOSTNAME_STRICT_HTTPS
            #   value: "true"
            # - name: TZ
            #   value: 'Europe/Berlin'
          ports:
            - name: keycloak-http
              containerPort: 8080
              # protocol: TCP
            # - name: keycloak-https
            #   containerPort: 8443
            #   protocol: TCP
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /health/ready
          #     port: 8080
          #   initialDelaySeconds: 250
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health/live
          #     port: 8080
          #   initialDelaySeconds: 500
          #   periodSeconds: 30
